namespace SpriteKind {
    export const pet = SpriteKind.create()
    export const XP = SpriteKind.create()
}
namespace StatusBarKind {
    export const XP = StatusBarKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level4`)
    tiles.placeOnTile(zendora, tiles.getTileLocation(16, 18))
})
scene.onOverlapTile(SpriteKind.Enemy, assets.tile`water`, function (sprite2, location2) {
    characterAnimations.loopFrames(
    crindos,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    500,
    characterAnimations.rule(Predicate.Moving)
    )
    if (crindos.tileKindAt(TileDirection.Left, assets.tile`water2`)) {
        crindos.x += -1
    } else if (crindos.tileKindAt(TileDirection.Right, assets.tile`water2`)) {
        crindos.x += 1
    } else if (crindos.tileKindAt(TileDirection.Top, assets.tile`water2`)) {
        crindos.y += 1
    } else if (crindos.tileKindAt(TileDirection.Bottom, assets.tile`water2`)) {
        crindos.y += -1
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`gras`, function (sprite11, location11) {
    controller.moveSprite(zendora, 100, 100)
    characterAnimations.loopFrames(
    zendora,
    assets.animation`zendora_loop_links`,
    500,
    characterAnimations.rule(Predicate.Moving)
    )
})
scene.onOverlapTile(SpriteKind.Enemy, sprites.castle.tilePath5, function (sprite10, location10) {
    crindos.follow(zendora, 50)
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_rechts`,
    500,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_links`,
    500,
    characterAnimations.rule(Predicate.MovingLeft)
    )
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_stil`,
    2000,
    characterAnimations.rule(Predicate.NotMoving)
    )
})
scene.onOverlapTile(SpriteKind.Enemy, assets.tile`water2`, function (sprite5, location5) {
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_zwem_links`,
    500,
    characterAnimations.rule(Predicate.MovingLeft)
    )
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_zwem_boven`,
    500,
    characterAnimations.rule(Predicate.MovingUp)
    )
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_zwem_rechts`,
    500,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    crindos,
    assets.animation`crindos_zwem_beneden`,
    500,
    characterAnimations.rule(Predicate.MovingDown)
    )
    crindos.follow(zendora, 20)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`water`, function (sprite3, location3) {
    controller.moveSprite(zendora, 70, 70)
    if (swim == 0) {
        swim = 1
        info.startCountdown(10)
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (weapon == "jes") {
        if (crindos.x - zendora.x <= 50 && crindos.x - zendora.x >= -50 && (crindos.y - zendora.y <= 50 && crindos.y - zendora.y >= -50)) {
            crindos_statusbar.value += -10
        }
    }
    pause(500)
})
info.onCountdownEnd(function () {
    while (zendora.tileKindAt(TileDirection.Center, assets.tile`water`)) {
        health_bar.value += -1e-16
    }
})
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    sprites.destroy(crindos)
    mySprite2 = sprites.create(assets.image`XP`, SpriteKind.XP)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`water2`, function (sprite7, location7) {
    swim = 0
    info.stopCountdown()
    controller.moveSprite(zendora, 70, 70)
    characterAnimations.loopFrames(
    zendora,
    assets.animation`zendora_loop_links`,
    500,
    characterAnimations.rule(Predicate.MovingLeft)
    )
    characterAnimations.loopFrames(
    zendora,
    assets.animation`old_`,
    500,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    zendora,
    assets.animation`Zendora_loop_boven`,
    500,
    characterAnimations.rule(Predicate.MovingUp)
    )
    characterAnimations.loopFrames(
    zendora,
    assets.animation`loop_naar_beneden`,
    500,
    characterAnimations.rule(Predicate.MovingDown)
    )
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.gameOver(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`woestijngrond1`, function (sprite8, location8) {
    controller.moveSprite(zendora, 100, 100)
    characterAnimations.loopFrames(
    zendora,
    assets.animation`zendora_loop_links`,
    500,
    characterAnimations.rule(Predicate.Moving)
    )
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairLarge, function (sprite12, location12) {
    tiles.setCurrentTilemap(tilemap`level4`)
    tiles.placeOnTile(zendora, tiles.getTileLocation(12, 8))
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite13, otherSprite) {
    health_bar.value += -1
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tilePath5, function (sprite9, location9) {
    controller.moveSprite(zendora, 100, 100)
    characterAnimations.loopFrames(
    zendora,
    assets.animation`zendora_loop_links`,
    500,
    characterAnimations.rule(Predicate.MovingLeft)
    )
    characterAnimations.loopFrames(
    zendora,
    assets.animation`loop_naar_beneden`,
    500,
    characterAnimations.rule(Predicate.MovingUp)
    )
    characterAnimations.loopFrames(
    zendora,
    assets.animation`old`,
    500,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    zendora,
    assets.animation`loop_naar_beneden`,
    500,
    characterAnimations.rule(Predicate.MovingDown)
    )
})
let mySprite2: Sprite = null
let swim = 0
let crindos_statusbar: StatusBarSprite = null
let health_bar: StatusBarSprite = null
let crindos: Sprite = null
let zendora: Sprite = null
let weapon = ""
weapon = "no"
tiles.setCurrentTilemap(tilemap`woestijnmap`)
zendora = sprites.create(assets.image`zendor`, SpriteKind.Player)
crindos = sprites.create(assets.image`crindos`, SpriteKind.Enemy)
let tankhond = sprites.create(assets.image`tankhond`, SpriteKind.pet)
health_bar = statusbars.create(20, 4, StatusBarKind.Health)
crindos_statusbar = statusbars.create(20, 4, StatusBarKind.Health)
let XP_bar = statusbars.create(20, 4, StatusBarKind.XP)
XP_bar.value = 0
XP_bar.setColor(7, 15)
health_bar.setColor(7, 2)
crindos_statusbar.setColor(7, 2)
XP_bar.attachToSprite(zendora, 4, 0)
health_bar.attachToSprite(zendora, 10, 0)
crindos_statusbar.attachToSprite(crindos, 4, 0)
tiles.placeOnTile(crindos, tiles.getTileLocation(87, 150))
crindos.follow(zendora, 50)
controller.moveSprite(zendora, 100, 100)
scene.cameraFollowSprite(zendora)
tiles.placeOnTile(zendora, tiles.getTileLocation(60, 120))
swim = 0
characterAnimations.loopFrames(
zendora,
assets.animation`zendora_loop_links`,
500,
characterAnimations.rule(Predicate.MovingLeft)
)
characterAnimations.loopFrames(
zendora,
assets.animation`loop_naar_beneden`,
100,
characterAnimations.rule(Predicate.MovingDown)
)
characterAnimations.loopFrames(
zendora,
assets.animation`zendora_loop_rechts0`,
500,
characterAnimations.rule(Predicate.MovingRight)
)
characterAnimations.loopFrames(
zendora,
assets.animation`Zendora_loop_boven`,
100,
characterAnimations.rule(Predicate.MovingUp)
)
characterAnimations.loopFrames(
crindos,
[img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    .......................f......
    ...............f..fffff7f.....
    ..............f7ff7777f7f.....
    ..............f777777777f..f..
    ..............f77127127f..fef.
    ...............f7777777f..fe5f
    ...............f7f11f7f..fee55
    ................f7ff77f.f5e555
    ...............ff77777ff.fe55f
    ..............f666677666ffe5f.
    ..............f766666667ffef..
    ..............f7767666777fef..
    ..............f7767666f77eef..
    ..............f7766676f77e7f..
    ..............f7766666ffee7f..
    ...............ff66bbbffeff...
    ................fbbb7bffef....
    ................f7bfbbf.f.....
    ................fbbfbbbf......
    ................fbbffbbf......
    ................f77ffb7f......
    ................f777f777f.....
    .................fff.fff......
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    .......................f......
    ...............f..fffff7f.....
    ..............f7ff7777f7f.....
    ..............f777777777f..f..
    ..............f77127127f..fef.
    ...............f7777777f..fe5f
    ...............f7f11f7f..fee55
    ................f7ff77f.f5e555
    ...............ff77777ff.fe55f
    ..............f666677666ffe5f.
    ..............f766666667ffef..
    ..............f7767666777fef..
    ..............f7767666f77eef..
    ..............f7766676f77e7f..
    ..............f7766666ffee7f..
    ...............ff66bbbffeff...
    ................fbbb7bffef....
    ...............fbbbfbbf.f.....
    ...............fbbffbbbf......
    ..............fbbbf.fbbf......
    .............f77bf..fb7f......
    ..............f77f..f777f.....
    ...............ff....fff......
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    .......................f......
    ...............f..fffff7f.....
    ..............f7ff7777f7f.....
    ..............f777777777f..f..
    ..............f77127127f..fef.
    ...............f7777777f..fe5f
    ...............f7f11f7f..fee55
    ................f7ff77f.f5e555
    ...............ff77777ff.fe55f
    ..............f666677666ffe5f.
    ..............f766666667ffef..
    ..............f7767666777fef..
    ..............f7767666f77eef..
    ..............f7766676f77e7f..
    ..............f7766666ffee7f..
    ...............ff66bbbffeff...
    .............ffffbbb7bffef....
    ............f77bb7bfbbf.f.....
    ............f77bbbffbbbf......
    ............f7ffff..fbbf......
    .............f......fb7f......
    ....................f777f.....
    .....................fff......
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    .......................f......
    ...............f..fffff7f.....
    ..............f7ff7777f7f.....
    ..............f777777777f..f..
    ..............f77127127f..fef.
    ...............f7777777f..fe5f
    ...............f7f11f7f..fee55
    ................f7ff77f.f5e555
    ...............ff77777ff.fe55f
    ..............f666677666ffe5f.
    ..............f766666667ffef..
    ..............f7767666777fef..
    ..............f7767666f77eef..
    ..............f7766676f77e7f..
    ..............f7766666ffee7f..
    ...............ff66bbbffeff...
    ................fbbb7bffef....
    ................f7bfbbf.f.....
    ................fbbfbbbf......
    ................fbbffbbf......
    ................f77ffb7f......
    ................f777f777f.....
    .................fff.fff......
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    .......................f......
    ...............f..fffff7f.....
    ..............f7ff7777f7f.....
    ..............f777777777f.....
    ..............f77127127f......
    ...............f7777777f......
    ...............f7f11f7f.......
    ................f7ff77f.......
    ...............ff77777ff...fff
    ..............f666677666f.f5e5
    ..............f766666667f.fee5
    ..............f7767666777ffe55
    ..............f7767666f777ee5f
    ..............f7766676ff77e7f.
    ..............f7766666f.fee7f.
    ...............ff66bbbf.fe7f..
    ................fbbb7bffeef...
    ................f7bfbbfeef....
    ................fbbbbbfef.....
    ................fbbbbf.f......
    ................f77bf.........
    ................f777f.........
    .................fff..........
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    .......................f......
    ...............f..fffff7f.....
    ..............f7ff7777f7f.....
    ..............f777777777f.....
    ..............f77127127f......
    ...............f7777777f...f..
    ...............f7f11f7f...fef.
    ................f7ff77f..ffe5f
    ...............ff77777fff5ee55
    ..............f666677666ffe55f
    ..............f766666667ffe5f.
    ..............f7767666777eef..
    ..............f7767666f77ef...
    ..............f7766676f7eef...
    ..............f7766666ffef....
    ...............ff66bbbfeef....
    ................fbbb7bfef.....
    ...............ff7b.bbff......
    ..............f7bbbbbbf.......
    ..............f77bbbff........
    ..............f7f77f..........
    ...............ff777f.........
    .................fff..........
    ..............................
    `],
500,
characterAnimations.rule(Predicate.MovingRight)
)
characterAnimations.loopFrames(
crindos,
[img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ......f........................
    .....f7fffff..f................
    .....f7f7777ff7f...............
    ..f..f777777777f...............
    .fef..f72172177f...............
    f5ef..f7777777f................
    55eef..f7f11f7f................
    555e5f.f77ff7f.................
    f55ef.ff77777ff................
    .f5eff666776666f...............
    ..feff766666667f...............
    ..fef7776667677f...............
    ..fee77f6667677f...............
    ..f7e77f6766677f...............
    ..f7eeff6666677f...............
    ...ffeffbbb66ff................
    ....feffb7bbbf.................
    .....fffbbfb7f.................
    ......fbbbfbbf.................
    ......fbbffbbf.................
    ......f7bff77f.................
    .....f777f777f.................
    ......fff.fff..................
    ...............................
    `,img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ......f........................
    .....f7fffff..f................
    .....f7f7777ff7f...............
    ..f..f777777777f...............
    .fef..f72172177f...............
    f5ef..f7777777f................
    55eef..f7f11f7f................
    555e5f.f77ff7f.................
    f55ef.ff77777ff................
    .f5eff666776666f...............
    ..feff766666667f...............
    ..fef7776667677f...............
    ..fee77f6667677f...............
    ..f7e77f6766677f...............
    ..f7eeff6666677f...............
    ...ffeffbbb66ff................
    ....feffb7bbbf.................
    .....f.fbbfbbbf................
    ......fbbbffbbf................
    ......fbbf.fbbbf...............
    ......f7bf..fb77f..............
    .....f777f..f77f...............
    ......fff....ff................
    ...............................
    `,img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ......7........................
    ......7.7777..7................
    ......777777777................
    ..e....72172177................
    .5e....7777777.................
    55ee....7f11f7.................
    555e5...77ff7..................
    .55e....77777..................
    ..5e..666776666................
    ...e..766666667................
    ...e.7776667677................
    ...ee77.6667677................
    ...7e77.6766677................
    ...7ee..6666677................
    .....e..bbb66..................
    .....e..b7bbb..................
    ........bb.b7bb77..............
    .......bbb..bbb77..............
    .......bb.......7..............
    .......7b......................
    ......777......................
    ...............................
    ...............................
    `,img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ......7........................
    ......7.7777..7................
    ......777777777................
    ..e....72172177................
    .5e....7777777.................
    55ee....7f11f7.................
    555e5...77ff7..................
    .55e....77777..................
    ..5e..666776666................
    ...e..766666667................
    ...e.7776667677................
    ...ee77.6667677................
    ...7e77.6766677................
    ...7ee..6666677................
    .....e..bbb66..................
    .....e..b7bbb..................
    ........bb.b7..................
    .......bbb.bb..................
    .......bb..bb..................
    .......7b..77..................
    ......777.777..................
    ...............................
    ...............................
    `,img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ......7........................
    ......7.7777..7................
    ......777777777................
    .......72172177................
    .......7777777.................
    ........7f11f7.................
    ........77ff7..................
    ........77777..................
    5e5...666776666................
    5ee...766666667................
    55e..7776667677................
    .5ee777.6667677................
    ..7e77..6766677................
    ..7ee...6666677................
    ...7e...bbb66..................
    ....ee..b7bbb..................
    .....ee.bb.b7..................
    ......e.bbbbb..................
    .........bbbb..................
    ..........b77..................
    ..........777..................
    ...............................
    ...............................
    `,img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ......7........................
    ......7.7777..7................
    ......777777777................
    .......72172177................
    .......7777777.................
    ..e.....7f11f7.................
    .5e.....77ff7..................
    55ee5...77777..................
    .55e..666776666................
    ..5e..766666667................
    ...ee7776667677................
    ....e77.6667677................
    ....ee7.6766677................
    .....e..6666677................
    .....ee.bbb66..................
    ......e.b7bbb..................
    ........bb.b7..................
    ........bbbbbb7................
    ..........bbb77................
    ...........77.7................
    ..........777..................
    ...............................
    ...............................
    `],
500,
characterAnimations.rule(Predicate.MovingLeft)
)
characterAnimations.loopFrames(
crindos,
[img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ......7.......................
    ......7.7777..7...............
    ......777777777...............
    .......72172177...............
    ..e....7777777................
    .5e.....7f11f7................
    55ee....77ff7.................
    555e5...77777.................
    .55e..666776666...............
    ..5e..766666667...............
    ...e.7766766677...............
    ...e.7776667677...............
    ...ee77.6667677...............
    ...7e77.6766677...............
    ...7ee..6666677...............
    .....e..bbb66.................
    .....e..b7bbb.................
    ........bb.b7.................
    .......bbb.bb.................
    .......bb..bb.................
    .......7b..77.................
    ......777.777.................
    ..............................
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ......7.......................
    ......7.7777..7...............
    ......777777777...............
    ..e....72172177...............
    .5e....7777777................
    55ee....7f11f7................
    555e5...77ff7.................
    .55e....77777.................
    ..5e..666776666...............
    ...e.7766666667...............
    ...e.7776667677...............
    ...ee77.6667677...............
    ...7e77.6766677...............
    ...7ee..6666677...............
    .....e..bbb66.................
    .....e..b7bbb.................
    ........bb.b7.................
    .......bbb.bb.................
    .......bb..bb.................
    .......7b..77.................
    ......777.777.................
    ..............................
    ..............................
    `,img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ......7.......................
    ......7.7777..7...............
    ......777777777...............
    ..e....73373377...............
    .5e....7777777................
    55ee....7f11f7................
    555e5...77ff7.................
    .55e....77777.................
    ..5e..666776666...............
    ...e.7766666667...............
    ...e.7776667677...............
    ...ee77.6667677...............
    ...7e77.6766677...............
    ...7ee..6666677...............
    .....e..bbb66.................
    .....e..b7bbb.................
    ........bb.b7.................
    .......bbb.bb.................
    .......bb..bb.................
    .......7b..77.................
    ......777.777.................
    ..............................
    ..............................
    `],
2000,
characterAnimations.rule(Predicate.NotMoving)
)
